name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Build Docker Image
      run: |
        docker build -t shrathan/devops-todo-app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag shrathan/devops-todo-app shrathan/devops-todo-app:latest
        docker push shrathan/devops-todo-app:latest

    - name: Set up SSH key for deployment
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}

    - name: Deploy Application on Ubuntu Server
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_HOST }} << EOF
        cd /home/ubuntu/devops_todo
        docker-compose down
        docker-compose pull
        docker-compose up -d
        EOF
